app:
  name: "UltraFit"
  version: "1.0.0"
  environment: "production"
  debug: false
  language: "zh"

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  host: "${DB_HOST:localhost}"
  port: 3306
  user: "${DB_USER:root}"
  password: "${DB_PASSWORD}"
  name: "${DB_NAME:shield}"
  timezone: "Asia/Shanghai"
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: "1h"
  log_level: "warn"
  slow_query_threshold: "100ms"
  # 迁移控制配置 - 生产环境禁用自动迁移
  enable_auto_migrate: false
  migration_mode: "disabled"

log:
  level: "info"
  format: "json"
  output: "stdout"

# 生产环境可选配置 - 根据需要启用

# jaeger:
#   otlp_url: "${JAEGER_OTLP_URL:http://localhost:4318/v1/traces}"
#   sample_rate: 0.1
#   enabled: true

redis:
  addrs: ["${REDIS_ADDR:localhost:6379}"]
  password: "${REDIS_PASSWORD}"
  db: 0
  key_prefix: "ultrafit:prod:"

auth:
  jwt:
    secret: "${JWT_SECRET}"
    expires_in: "24h"
    refresh_expires: "168h"
    issuer: "shield"
  # 验证码配置 - 生产环境强制验证
  captcha_mode: "strict"      # 生产环境强制验证码
  dev_bypass_code: ""         # 生产环境不设置绕过码

# http_client:
#   timeout: 30
#   retry_count: 3
#   enable_trace: true

captcha:
  enabled: true
  type: "digit"
  width: 160
  height: 60
  length: 4
  noise_count: 8
  expiration: "5m"